input_data_type: dmri
input_data:
  participants: 
    file: /path/to/participants.tsv
    sep: "\t"
    index_col: participant_id
  bet_binary_mask: /path/to/dataset/{participant_id}/bet_binary_mask.nii.gz
  xfm: /path/to/dataset/{participant_id}/xfm.nii.gz
  inv_xfm: /path/to/dataset/{participant_id}/inv_xfm.nii.gz
  samples: /path/to/dataset/{participant_id}/samples/merged
  seed_mask: /path/to/region_of_interest.nii.gz
  target_mask: /path/to/MNI152GM.nii.gz

parameters:
  masking:
    median_filter: false
    median_filter_dist: 1
    resample_to_mni: true
    threshold: 0.0
    upsample_seed_to: [1, 1, 1]
    downsample_target_to: [3, 3, 3]
  connectivity:
    pca_transform: 0.95
    dist_thresh: 5.0
    loop_check: true
    c_thresh: 0.2
    step_length: 0.5
    n_samples: 200
    n_steps: 2000
    correct_path_distribution: true
    cleanup_fsl: true
    cubic_transform: true
  clustering:
    algorithm: auto
    group_method: mode
    init: random
    internal_validity_metrics: ['silhouette_score', 'davies_bouldin_score', 'calinski_harabasz_score']
    linkage: complete
    max_iter: 10000
    n_clusters: [2, 3, 4, 5]
    n_init: 256
    similarity_metric: adjusted_rand_score
  summary:
    figure_format: png

