input_data_type: rsfmri
input_data:
  participants: 
    file: /path/to/participants.tsv
    sep: "\t"
    index_col: participant_id
  time_series:
    file: /path/to/dataset/{participant_id}/time_series.nii.gz
    validate_shape: true
  confounds: 
    file: /path/to/dataset/{participant_id}/confounds.tsv
    sep: "\t"
    usecols: ['constant', 'linearTrend', 'wm', 'csf', 'motion-*']
  seed_mask: /path/to/region_of_interest.nii.gz
  target_mask: /path/to/MNI152GM.nii.gz

parameters:
  masking:
    del_seed_expand: 0
    del_seed_from_target: false
    median_filter: false
    median_filter_dist: 1
    resample_to_mni: true
    subsample: true
    threshold: 0.0
  connectivity:
    arctanh_transform: true
    pca_transform: null
    high_pass: 0.01
    low_pass: 0.08
    smoothing_fwhm: null
    seed_low_variance_threshold: 0.05
    target_low_variance_threshold: 0.1
    tr: 0.72
    compress: true
  clustering:
    algorithm: auto
    group_method: mode
    init: random
    internal_validity_metrics: ['silhouette_score', 'davies_bouldin_score', 'calinski_harabasz_score']
    linkage: complete
    max_iter: 10000
    n_clusters: [2, 3, 4, 5]
    n_init: 256
    similarity_metric: adjusted_rand_score
  summary:
    figure_format: png

